server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identify_service"
    username: root
    password: dat082001
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "QDToOvSHVXbiPzVe7HAekb05/oLVCJdaknBvDU/VBIvLcRNT4VxAqZUHA/mdXHEj"
  valid-duration: 3600 # in seconds
  refreshable-duration: 360000 #seconds